#!/bin/sh
#
# ~/.config/sh/xdg - XDG Base Directory Specification

# http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
test "$XDG_BIN_HOME"    || export XDG_BIN_HOME="$HOME/.local/bin"
test "$XDG_CACHE_HOME"  || export XDG_CACHE_HOME="$HOME/.cache"
test "$XDG_CONFIG_HOME" || export XDG_CONFIG_HOME="$HOME/.config"
test "$XDG_DATA_HOME"   || export XDG_DATA_HOME="$HOME/.local/share"
test "$XDG_LIB_HOME"    || export XDG_LIB_HOME="$HOME/.local/lib"

# Environment variables respecting programs:
export GIT_SSH_COMMAND="ssh -F $XDG_CONFIG_HOME/ssh/config"
export GNUPGHOME="$HOME/.gnupg"
#export LESSHISTFILE="$XDG_DATA_HOME/less/history"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
export NPM_CONFIG_DEVDIR="$XDG_CACHE_HOME/node-gyp"
export PYLINTHOME="$XDG_DATA_HOME/pylint"
export PYLINTRC="$XDG_CONFIG_HOME/pylint/pylintrc"
export PYTHONHISTORY="$XDG_CACHE_HOME/python/python_history"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc.py"
export thumbnail_dir="$XDG_CACHE_HOME/thumbnails/neofetch"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export YARN_CACHE_FOLDER="$XDG_CACHE_HOME/yarn"
export AZURE_CONFIG_DIR="$XDG_CONFIG_HOME/azure"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH_COMPDUMP="$XDG_CACHE_HOME/zsh/zcompdump-${SHORT_HOST}-${ZSH_VERSION}"
export _Z_DATA="$XDG_DATA_HOME/z/data"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export CCACHE_DIR="$XDG_CACHE_HOME/ccache"

# export GEM_HOME="$XDG_DATA_HOME/gem"
# export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"

# export MU_HOME="$XDG_CACHE_HOME/mu"
# export MYSQL_HISTFILE="$XDG_CACHE_HOME/mysql.history"
